server:
  port: 9002

spring:
  application:
    name: movie

eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url:  # 客户端注册地址
      defaultZone: http://127.0.0.1:9003/eureka # 注册到哪里, 也就是Eureka Server的地址
  instance:
    prefer-ip-address: true # 将ip地址注册到Eureka Server

feign:
  hystrix:
    enabled: true # 开启Feign熔断功能

## 修改Ribbon的负载均衡算法
#user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
