server:
  port: 9001

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#  freemarker:
#    cache: false    #页面不加载缓存，修改即时生效
#  redis:
#    port: 6379
#    host: localhost
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 0
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # 全局主键策略
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1

eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url:  # 客户端注册地址
      defaultZone: http://127.0.0.1:9003/eureka # 注册到哪里, 也就是Eureka Server的地址
  instance:
    prefer-ip-address: true # 将ip地址注册到Eureka Server
